DROP TABLE IF EXISTS SY_ITEM_HXITEM2;
CREATE TABLE SY_ITEM_HXITEM2 AS
SELECT
	SY_TEST_ITEMS.ITEM_ID
	, SY_TEST_ITEMS.CAT_ID
	, SY_ITEM_TERMS.TERMMS
	, HXITEM_ID
	, HXITEM_CAT_ID
	, HXITEM_TERMS
FROM SY_TEST_ITEMS
LEFT OUTER JOIN SY_ITEM_TERMS
ON SY_TEST_ITEMS.ITEM_ID = SY_ITEM_TERMS.ITEM_ID
LEFT OUTER JOIN SY_CAT_DPCAT
ON SY_TEST_ITEMS.CAT_ID = SY_CAT_DPCAT.CAT_ID
LEFT OUTER JOIN
(
	SELECT
	SY_TEST_ITEMS.ITEM_ID AS HXITEM_ID
	, SY_TEST_ITEMS.CAT_ID AS HXITEM_CAT_ID
	, SY_ITEM_TERMS.TERMMS AS HXITEM_TERMS
	FROM SY_TEST_ITEMS
	LEFT OUTER JOIN SY_ITEM_TERMS
	ON SY_TEST_ITEMS.ITEM_ID = SY_ITEM_TERMS.ITEM_ID
)A
ON SY_CAT_DPCAT.DPITEM_CAT_ID = A.HXITEM_CAT_ID
WHERE !ISNULL(A.HXITEM_ID);

DROP TABLE IF EXISTS SY_ITEM_YCITEM2;
CREATE TABLE SY_ITEM_YCITEM2
(
   	ITEM_ID BIGINT
	, YCITEM_ID BIGINT
	, YCITEM_DPD DOUBLE
);

JAR SY_PREDICT2.jar;
