DROP TABLE IF EXISTS SY_ITEMS_HX3;
CREATE TABLE SY_ITEMS_HX3 AS
SELECT
	SY_ITEMS.ITEM_ID
	, CAT_ID
	, TERMS
FROM SY_ITEMS
LEFT OUTER JOIN
(
	SELECT ITEM_ID FROM SY_ITEM_DPITEMS
	UNION ALL
	SELECT ITEM_ID FROM TEST_ITEMS
	UNION ALL
	SELECT ITEM_ID FROM USER_BOUGHT_HISTORY
)A
ON SY_ITEMS.ITEM_ID = A.ITEM_ID
WHERE ISNULL(A.ITEM_ID);

DROP TABLE IF EXISTS SY_ITEM_HXITEM3;
CREATE TABLE SY_ITEM_HXITEM3 AS
SELECT
	SY_TEST_ITEMS.ITEM_ID
	, SY_TEST_ITEMS.CAT_ID
	, SY_ITEM_TERMS.TERMMS
	, HXITEM_ID
	, HXITEM_CAT_ID
	, HXITEM_TERMMS
FROM SY_TEST_ITEMS
LEFT OUTER JOIN SY_ITEM_TERMS
ON SY_TEST_ITEMS.ITEM_ID = SY_ITEM_TERMS.ITEM_ID
LEFT OUTER JOIN SY_CAT_DPCAT
ON SY_TEST_ITEMS.CAT_ID = SY_CAT_DPCAT.CAT_ID
LEFT OUTER JOIN
(
	SELECT
		SY_ITEMS_HX3.ITEM_ID AS HXITEM_ID
		, SY_ITEMS_HX3.CAT_ID AS HXITEM_CAT_ID
		, SY_ITEM_TERMS.TERMMS AS HXITEM_TERMMS
	FROM SY_ITEMS_HX3
	LEFT OUTER JOIN SY_ITEM_TERMS
	ON SY_ITEMS_HX3.ITEM_ID = SY_ITEM_TERMS.ITEM_ID
)A
ON SY_CAT_DPCAT.DPCAT_ID = A.HXITEM_CAT_ID
WHERE !ISNULL(A.HXITEM_ID);

DROP TABLE IF EXISTS SY_ITEM_YCITEM3;
CREATE TABLE SY_ITEM_YCITEM3
(
	ITEM_ID BIGINT
	, YCITEM_ID BIGINT
	, YCITEM_DPD DOUBLE
);

JAR -libjars sy_predict3.jar
