DROP TABLE IF EXISTS SY_ITEMS;
CREATE TABLE SY_ITEMS AS
SELECT ITEM_ID, CAT_ID, TERMS
FROM DIM_ITEMS;

DROP TABLE IF EXISTS SY_TEST_ITEMS;

CREATE TABLE SY_TEST_ITEMS AS
SELECT TEST_ITEMS.ITEM_ID, CAT_ID, TERMS
FROM TEST_ITEMS

LEFT OUTER JOIN SY_ITEMS
ON TEST_ITEMS.ITEM_ID = SY_ITEMS.ITEM_ID;

DROP TABLE IF EXISTS SY_TEST_CATS;
CREATE TABLE SY_TEST_CATS A
SELECT DISTINCT CAT_ID
FROM SY_TEST_ITEMS;
